---
services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - source
    volumes_from:
      - source
    networks:
      - webnet

  db:
    image: mysql:5.7
    volumes_from:
      - source
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - webnet

  source:
    image: alpine:latest
    container_name: source
    volumes:
      - ${SITE_PATH}:/var/www/html
    networks:
      - webnet
networks:
  webnet: